### ISSUE TITLE
How To install and use it?

### ISSUE THREAD

**Issue by ciaotesla** [natlamir/PiperUI#11]
Hi,
can someone explain how to install and use this webui with Piper TTS? What are the requirements?
There is no information on how to do it.

thx

**Comment by natlamir** [comment]
I added some more details on the readme. This is on Windows, will need to extract the contents of the release files from the Piper github to the bin debug folder, then should be able to run the app through visual studio. Let me know if you have any issues getting it running.

**Comment by natlamir** [comment]
For just using the application, it is in the Releases: [PiperUI.zip](https://github.com/natlamir/PiperUI/releases/download/v1.2.0/PiperUI.zip)
