### ISSUE TITLE
Vietnamese language not working properly

### ISSUE THREAD

**Issue by UncleBob2** [natlamir/PiperUI#2]
Thanks for creating the GUI, I was thinking of doing the same thing but you beat me to it. It is downloading the correct Vietnamese models but the text is not being sent in UTF8 format; hence, it is not Vietnamese audio output.

**Comment by natlamir** [comment]
Good catch, I have made the fix locally, and will merge it with some other changes in about 1-2 days. thanks!

**Comment by UncleBob2** [comment]
Thank you very much. Greatly appreciated.
