### ISSUE TITLE
Feature Request for Speech Speed

### ISSUE THREAD

**Issue by UncleBob2** [natlamir/PiperUI#3]
Is it possible that you can add a slider to control the speech speed per the example below? 

https://github.com/phatjkk/vits-tts-vietnamese

**Comment by natlamir** [comment]
Interesting, it looks like that is using the onnxruntime to run inference on the model directly. I will do some research on how to use  it from the documentation from the [onnxruntime site](https://onnxruntime.ai/), thanks.

**Comment by hecko-yes** [comment]
You can do it with piper.exe too, using the `--length_scale` parameter. For example, setting it to 2 makes everything take twice as long. (You might want to run `piper.exe --help` to see the full list of parameters.)

**Comment by natlamir** [comment]
> You can do it with piper.exe too, using the `--length_scale` parameter. For example, setting it to 2 makes everything take twice as long. (You might want to run `piper.exe --help` to see the full list of parameters.)

I will check that out and add it to the UI. Thanks!
