### ISSUE TITLE
Suggestion: Increase Text length when copy pasting, and audio playback? 

### ISSUE THREAD

**Issue by FemBoxbrawl** [natlamir/PiperUI#6]
Hey just asking if you could add a "play button" when generating audio, but also increase the length of the text to speech? either way, I am glad you made this, because with coding it would have been hell

**Comment by Fouladi-K** [comment]
same problem here. can not copy  paste multiple paragraphs.

**Comment by Fouladi-K** [comment]
I found that for long text in the **Windows PowerShell** we can use:
Get-Content text.txt | .\piper.exe -m models\en_US-ryan-high.onnx -f output\output.wav
you must download model first and place text.txt in folder.

only use Windows PowerShell not cmd.
