### ISSUE TITLE
Feedback on lip2sync

### ISSUE THREAD

**Issue by AIhasArrived** [natlamir/PiperUI#7]
Hello
I could not write a message on that repo So I am writing it here.
- First of all, I found your youtube videos and choice of voices hilarious! https://www.youtube.com/watch?v=w4PFot5csx0
- Where did you find that voice? Do you use tts or some PARTICULAR repo/programm instead? I like that voice
- I will try your UI now but I am not sure it will be much faster than what I am used to (I need to lip sync LONG videos) Hope it is fast, my question is do you know how to make the script run FASTER ((by using MORE GPU))??? if yes please tell me every trick. 

Thanks

**Comment by AIhasArrived** [comment]
@natlamir  I also got a problem when trying to run your UI (no wthat I followed your instructions and installed it)
Could you help please? (Do you have any form of contact anyway, optional)

**Comment by natlamir** [comment]
The voice I use is from Eleven Labs when I originally started making videos.
